name: Release

on:
    workflow_dispatch:
    workflow_run:
        workflows:
            - Test
        types:
            - completed

concurrency: ${{ github.workflow }}-${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}

permissions:
    contents: write
    pull-requests: write
    actions: write
    id-token: write

jobs:
    release:
        name: Release
        if: >
            github.event_name == 'workflow_dispatch' ||
            (
                github.event.workflow_run.conclusion == 'success' &&
                (
                    github.event.workflow_run.head_branch == 'master' ||
                    github.event.workflow_run.head_branch == 'v4' ||
                    github.event.workflow_run.head_branch == 'v1'
                )
            )
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}

            -   name: Setup Node.js
                uses: actions/setup-node@v6
                with:
                    node-version-file: .node-version
                    registry-url: https://registry.npmjs.org

            -   name: Upgrade npm
                run: npm i -g npm@latest

            -   name: Setup pnpm
                uses: pnpm/action-setup@v4

            -   name: Install Dependencies
                run: pnpm install

            -   name: Create Release Pull Request
                uses: changesets/action@v1
                with:
                    title: Version Packages for ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}
                    publish: pnpm release
                    createGithubReleases: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name) == 'master' }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    RELEASE_BRANCH: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.ref_name }}
