name: Release

on:
    workflow_dispatch:
    workflow_call:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: write
    pull-requests: write
    actions: write
    id-token: write

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.ref }}

            -   name: Setup Node.js
                uses: actions/setup-node@v6
                with:
                    node-version-file: .node-version

            -   name: Setup pnpm
                uses: pnpm/action-setup@v4

            -   name: Install Dependencies
                run: pnpm install

            -   name: Create Release Pull Request
                uses: changesets/action@v1
                with:
                    title: Version Packages for ${{ github.ref_name }}
                    publish: pnpm release
                    createGithubReleases: ${{ github.ref_name == 'master' }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
